### ISSUE TITLE
Want to work together?

### ISSUE THREAD

**Issue by DorianGray** [sourcelair/ceryx#2]
https://github.com/Olivine-Labs/waco-kid

I've been working on a drop in replacement for vulcand in openresty for a few days. It currently supports vulcand's Route syntax(host, header, method, and uri matching) and uses and ffi binding to libr3(https://github.com/c9s/r3) for the actual routing. It also uses an ffi cache for configuration, and updates the routing tree in the background only when changes occur. I get 15-20 million routes matched per second per core with this configuration on my laptop.

Currently it only supports etcd with vulcand's configuration format, but with some minor changes it could support ceryx as well! It uses an intermediate format stored in the cache for building routes, so only the portion of code for updating that config would need to change.

**Comment by akalipetis** [comment]
Hey @DorianGray, sorry for not getting back to you earlier. We're always open to collaborations,  would you like to share what you have in mind?

There's also another nice similar project I got by recently https://github.com/mashape/kong.
