### ISSUE TITLE
ceryx/Proxy/Dockerfile.xenial	- XFS User does not exists

### ISSUE THREAD

**Issue by george-mengelberg** [sourcelair/ceryx#23]
I built a docker image using _ceryx/Proxy/Dockerfile.xenial_ but starting an image based on the image failed as the xfs user did not exists.  I added `RUN useradd xfs` to the  dockerfile and was able to start it.

**Comment by akalipetis** [comment]
Hello @george-mengelberg - thanks for reporting. Can you please check that this is resolved with #24?

The actual issue was that Ubuntu images should use `www-data`.
