### ISSUE TITLE
Duplication of source parameter on PUT route?

### ISSUE THREAD

**Issue by JoshBrodieNZ** [sourcelair/ceryx#25]
Hey team,

Hoping to put together some quick notes on usage of the API. It seems as though the PUT route in https://github.com/sourcelair/ceryx/blob/master/api/ceryx/api/views.py requires a source both in the URL as well as requiring a source as an explicit parameter. Am I correct in my reading of this?

If I PUT {"target":"127.0.0.1:80"} to '/api/routes/test', I am told that a source is required.
I I PUT {"source":"test","target":"127.0.0.1:80"} to '/api/routes', the method is not allowed.

The only way I can get it to function is by submitting {"source":"test","target":"127.0.0.1:80"} to '/api/routes/any_words_here' where any_words_here is required but not used and doesn't have to match the source parameter.

**Comment by akalipetis** [comment]
Hey @JoshBrodieNZ - you are correct. I have drafted a PR that should fix this: #26

**Comment by akalipetis** [comment]
Closing after #26 was merged.
