### ISSUE TITLE
How to populate redis ?

### ISSUE THREAD

**Issue by Snowmanko** [sourcelair/ceryx#34]
Can you please post some example how to populate redis so I will be able to add "virtulhosts" and coresponting routes ? 

Thanks.

**Comment by parisk** [comment]
You can configure Ceryx about how to connect to and use a Redis server, with the following environment variables:

- `CERYX_REDIS_HOST`: the redis host to connect to - defaults to `127.0.0.1`
- `CERYX_REDIS_PORT`: the redis port to connect to - defaults to `6379`
- `CERYX_REDIS_PREFIX`: the redis prefix to use in keys - defaults to `ceryx`

[All configuration options are available in the README](https://github.com/sourcelair/ceryx#configuration).
