### ISSUE TITLE
Issue SSL certificates only for existing sources

### ISSUE THREAD

**Issue by coodix** [sourcelair/ceryx#36]
For now dynamic SSL doesn't check if host is in sources.

There is only mechanism to specify CERYX_SSL_PATTERN env var but it kills dynamism.

**Comment by parisk** [comment]
Thanks for the feedback @coodix!

Can you please explain your use case and what would be a more convenient way for you?

**Comment by coodix** [comment]
Hi @parisk,

The problem is that ceryx will try issuing certificates even for domains which are not in main routing table. 

Fro example, I have domain example.com which is pointing with all its subdomains (*.example.com) to same IP address. Despite I add only domain "service1.example.com", Ceryx will issue ssl certificate for "service2.example.com" if I try to access it.

**Comment by coodix** [comment]
Hi @parisk ! Did I explain well the issue?

**Comment by parisk** [comment]
Hi @coodix, sorry for being late to get on top of this!

You explained it really well and we agree that this is something that has to be fixed.

We do not have a plan on when we will start to work on this, but we will happily welcome a PR if you are interested 😄.

**Comment by parisk** [comment]
Closed in #39.
