### ISSUE TITLE
API usage

### ISSUE THREAD

**Issue by Dids** [sourcelair/ceryx#4]
I can't seem to wrap my head around the endpoints that the API uses, so all I get from is are 404 error codes.

I've tried GET/POST/PUT/DELETE etc. and from the Python code, I can't even seem to be able to find where the endpoints are defined at.

I don't suppose you could point me in the right direction?

**Comment by Dids** [comment]
Figured it out. So the endpoint is http://host:5555/route/ and the parameters are *source* and *target* (ie. domain.com for source and longerdomain.com for target, as I understood it).

I did notice that PUT requests didn't work, they had to be POST instead. At any rate, I guess this'll get me going and hopefully it'll point other people in the right direction as well.

**Comment by akalipetis** [comment]
Hello @Dids, the API needs documentation indeed. In order to help you out a bit:

The only difference is that the path is `/routes` and not `/route/` and then you can query routes by `/routes/domain.here.com`

Also, you can `PUT` at `/routes/domain.to.be.changed.com`.

**Comment by Dids** [comment]
Thanks @akalipetis, that makes things a lot simpler. :)

**Comment by akalipetis** [comment]
Ok, seems like we've left out some old paths for backwards compatibility :disappointed: which I had forgotten.

You can see the routes here: https://github.com/sourcelair/ceryx/blob/master/api/ceryx/api/__init__.py#L14

I was talking about:

* `/api/routes`
* `/api/routes/domain.here.com`

Sorry for the misunderstanding.

In any case, feel free to make a PR with docs for the API if you'd like, we'd :heart: that
