### ISSUE TITLE
Updated image on dockerhub

### ISSUE THREAD

**Issue by MiniCodeMonkey** [sourcelair/ceryx#46]
Hi there,

Big fan of Ceryx 👍 

Could you update the "official" dockerhub repo with a newer version? Looks like it hasn't been update for two months:
https://hub.docker.com/r/sourcelair/ceryx-proxy/tags/

Thanks!

**Comment by parisk** [comment]
Hi @MiniCodeMonkey, thanks for the kind words! We are happy that you are enjoying Ceryx.

You can find the new simplified image at https://hub.docker.com/r/sourcelair/ceryx/ 😁, which is built automatically when something gets merged into the `master` branch.
