### ISSUE TITLE
install lua-resty-auto-ssl 0.12.0 halts build

### ISSUE THREAD

**Issue by tomj59** [sourcelair/ceryx#52]
During the ceryx container build:

...

Step 5/10 : RUN /usr/local/openresty/luajit/bin/luarocks install lua-resty-auto-ssl 0.12.0
 ---> Running in 583e3c3268ff
Illegal instruction (core dumped)
ERROR: Service 'ceryx' failed to build: The command '/bin/sh -c /usr/local/openresty/luajit/bin/luarocks install lua-resty-auto-ssl 0.12.0' returned a non-zero code: 132

**Comment by parisk** [comment]
Hi Tom. Thanks for reporting this. This works fine for us on Docker for Mac at least.

On what system are you attempting to build the image? Can you send over the output of `docker version` and `docker info` please?

---

<details>
  <summary>docker build logs</summary>
  <pre>
paris at ceryx (master) ⠕ docker build --no-cache -t sourcelair/ceryx .
Sending build context to Docker daemon  23.04kB
Step 1/10 : FROM openresty/openresty:1.13.6.1-xenial
 ---> 57f354746dca
Step 2/10 : RUN mkdir -p /etc/letsencrypt &&    openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509         -subj '/CN=sni-support-required-for-valid-ssl'         -keyout /etc/ssl/resty-auto-ssl-fallback.key         -out /etc/ssl/resty-auto-ssl-fallback.crt
 ---> Running in f1fc328ee475
Generating a 2048 bit RSA private key
.............+++
..+++
writing new private key to '/etc/ssl/resty-auto-ssl-fallback.key'
-----
Removing intermediate container f1fc328ee475
 ---> 6ea31ccc08b0
Step 3/10 : ENV DOCKERIZE_VERSION=v0.6.1
 ---> Running in 55f88b8cf5bb
Removing intermediate container 55f88b8cf5bb
 ---> 729341808806
Step 4/10 : RUN curl -fSslL https://github.com/jwilder/dockerize/releases/download/${DOCKERIZE_VERSION}/dockerize-linux-amd64-${DOCKERIZE_VERSION}.tar.gz |     tar xzv -C /usr/local/bin/
 ---> Running in c24ec04ba72d
dockerize
Removing intermediate container c24ec04ba72d
 ---> 9ef97de27e99
Step 5/10 : RUN /usr/local/openresty/luajit/bin/luarocks install lua-resty-auto-ssl 0.12.0
 ---> Running in 08a1ac05b65d
Warning: The directory '/root/.cache/luarocks' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing /usr/local/openresty/luajit/bin/luarocks with sudo, you may want sudo's -H flag.
Installing https://luarocks.org/lua-resty-auto-ssl-0.12.0-1.src.rock
Missing dependencies for lua-resty-auto-ssl 0.12.0-1:
   lua-resty-http (not installed)

lua-resty-auto-ssl 0.12.0-1 depends on lua-resty-http (not installed)
Installing https://luarocks.org/lua-resty-http-0.12-0.src.rock
No existing manifest. Attempting to rebuild...
mkdir -p /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build
rm -f /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build/stamp-dehydrated-*
mkdir -p /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build/bin
curl -sSLo /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build/bin/dehydrated "https://raw.githubusercontent.com/lukas2511/dehydrated/0bc0bd13d6abdc027c58bec12f7c2d3198d3a677/dehydrated"
chmod +x /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build/bin/dehydrated
touch /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build/stamp-dehydrated-2-0bc0bd13d6abdc027c58bec12f7c2d3198d3a677
rm -f /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build/stamp-lua-resty-shell-*
curl -sSLo /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/lib/resty/auto-ssl/vendor/shell.lua "https://raw.githubusercontent.com/juce/lua-resty-shell/955243d70506c21e7cc29f61d745d1a8a718994f/lib/resty/shell.lua"
touch /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build/stamp-lua-resty-shell-955243d70506c21e7cc29f61d745d1a8a718994f
rm -f /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build/stamp-sockproc-*
mkdir -p /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build/bin
cd /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build && curl -sSLo sockproc-fc8ad3f15a7b2cf2eaf39663b90010efc55e207c.tar.gz "https://github.com/juce/sockproc/archive/fc8ad3f15a7b2cf2eaf39663b90010efc55e207c.tar.gz"
cd /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build && tar -xf sockproc-fc8ad3f15a7b2cf2eaf39663b90010efc55e207c.tar.gz
cd /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build/sockproc-fc8ad3f15a7b2cf2eaf39663b90010efc55e207c && make
make[1]: Entering directory '/tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build/sockproc-fc8ad3f15a7b2cf2eaf39663b90010efc55e207c'
gcc -Wall -Werror -o sockproc sockproc.c
make[1]: Leaving directory '/tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build/sockproc-fc8ad3f15a7b2cf2eaf39663b90010efc55e207c'
cp /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build/sockproc-fc8ad3f15a7b2cf2eaf39663b90010efc55e207c/sockproc /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build/bin/sockproc
chmod +x /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build/bin/sockproc
touch /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build/stamp-sockproc-2-fc8ad3f15a7b2cf2eaf39663b90010efc55e207c
install -d /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl
install -m 644 lib/resty/auto-ssl.lua /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl.lua
install -m 644 lib/resty/auto-ssl/init_master.lua /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/init_master.lua
install -m 644 lib/resty/auto-ssl/init_worker.lua /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/init_worker.lua
install -d /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/jobs
install -d /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/json_adapters
install -m 644 lib/resty/auto-ssl/json_adapters/cjson.lua /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/json_adapters/cjson.lua
install -m 644 lib/resty/auto-ssl/json_adapters/dkjson.lua /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/json_adapters/dkjson.lua
install -m 644 lib/resty/auto-ssl/jobs/renewal.lua /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/jobs/renewal.lua
install -d /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/servers
install -m 644 lib/resty/auto-ssl/servers/challenge.lua /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/servers/challenge.lua
install -m 644 lib/resty/auto-ssl/servers/hook.lua /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/servers/hook.lua
install -m 644 lib/resty/auto-ssl/ssl_certificate.lua /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/ssl_certificate.lua
install -d /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/ssl_providers
install -m 644 lib/resty/auto-ssl/ssl_providers/lets_encrypt.lua /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/ssl_providers/lets_encrypt.lua
install -m 644 lib/resty/auto-ssl/storage.lua /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/storage.lua
install -d /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/storage_adapters
install -m 644 lib/resty/auto-ssl/storage_adapters/file.lua /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/storage_adapters/file.lua
install -m 644 lib/resty/auto-ssl/storage_adapters/redis.lua /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/storage_adapters/redis.lua
install -d /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/utils
install -m 644 lib/resty/auto-ssl/utils/shell_execute.lua /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/utils/shell_execute.lua
install -m 644 lib/resty/auto-ssl/utils/start_sockproc.lua /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/utils/start_sockproc.lua
install -m 644 lib/resty/auto-ssl/utils/run_command.lua /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/utils/run_command.lua
install -d /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/vendor
install -m 644 lib/resty/auto-ssl/vendor/shell.lua /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/lua/resty/auto-ssl/vendor/shell.lua
install -d /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/bin/resty-auto-ssl
install -m 755 bin/letsencrypt_hooks /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/bin/resty-auto-ssl/letsencrypt_hooks
install -m 755 bin/start_sockproc /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/bin/resty-auto-ssl/start_sockproc
install -m 755 /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build/bin/dehydrated /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/bin/resty-auto-ssl/dehydrated
install -m 755 /tmp/luarocks_lua-resty-auto-ssl-0.12.0-1-fwmBfF/lua-resty-auto-ssl/build/bin/sockproc /usr/local/openresty/luajit/lib/luarocks/rocks/lua-resty-auto-ssl/0.12.0-1/bin/resty-auto-ssl/sockproc
lua-resty-http 0.12-0 is now installed in /usr/local/openresty/luajit (license: 2-clause BSD)

lua-resty-auto-ssl 0.12.0-1 is now installed in /usr/local/openresty/luajit (license: MIT)

Removing intermediate container 08a1ac05b65d
 ---> 680ffe56602b
Step 6/10 : COPY ./bin/entrypoint.sh /entrypoint.sh
 ---> 799fca1be7c9
Step 7/10 : ENTRYPOINT [ "/entrypoint.sh" ]
 ---> Running in d17d94d7d5c3
Removing intermediate container d17d94d7d5c3
 ---> 81ee023a4e46
Step 8/10 : COPY ./nginx/conf /usr/local/openresty/nginx/conf
 ---> 5f29f872af90
Step 9/10 : COPY ./nginx/lualib /usr/local/openresty/nginx/lualib
 ---> 216e0b761010
Step 10/10 : CMD ["/usr/local/openresty/bin/openresty", "-g", "daemon off;"]
 ---> Running in 0e3e98c76f9b
Removing intermediate container 0e3e98c76f9b
 ---> 6850deb20d2f
Successfully built 6850deb20d2f
Successfully tagged sourcelair/ceryx:latest
  </pre>
</details>

**Comment by parisk** [comment]
This looks like an OS failure.

Based on your logs, [this table about UNIX exit codes](http://tldp.org/LDP/abs/html/exitcodes.html) and [this table about UNIX signals](http://people.cs.pitt.edu/~alanjawi/cs449/code/shell/UnixSignals.htm), I understand that your build is being killed by signal 4 (SIGILL) from the OS, because it attempts to run an illegal instruction.

The only thing that changes between Docker builds (yours, ours and Docker Hub's) is the kernel of the host, so please give it a go and try running the build on another computer (try Docker for Mac or Docker for Windows or an Ubuntu LTS host).

Also, I see that your VM has <2GB of memory, is there any chance this is causing the build to fail?

I am closing this, since building Ceryx works on our infrastructure and on Docker Hub.

**Comment by keithy** [comment]
looks like missing sse4.2 instructions in the CPU?
