### ISSUE TITLE
Introduce balanced endpoints for Ceryx

### ISSUE THREAD

**Issue by akalipetis** [sourcelair/ceryx#6]
Ceryx currently supports only single endpoints to be placed for routes, aka `my.route.com -> my.backend.com:9999`

We could introduce more backends per route and load balance traffic in these routes, for example we could utilize [balancer](https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/balancer.md) Open-Resty module.

**Comment by parisk** [comment]
Sounds like this could have great usage for automatic deployments to production.

:+1:

**Comment by parisk** [comment]
Closing this. Clustering solutions like Docker Swarm and Kubernetes do an excellent job with balancing/routing based on DNS name resolution.

Let's do one thing and do it well!
