### ISSUE TITLE
Source route  Can't resources be http://127.0.0.1/wcm?

### ISSUE THREAD

**Issue by tanyo520** [sourcelair/ceryx#69]
![image](https://user-images.githubusercontent.com/5094034/61043603-46bd9000-a409-11e9-98e9-ba10638a0d6a.png)

**Comment by tanyo520** [comment]
How to configure multiple proxy addresses if the current server needs to configure

**Comment by parisk** [comment]
Hello there! `source` should be just a hostname (e.g. `your-domain.com`), no full URLs or paths are supported (yet).

Cheers 🥂.

**Comment by tanyo520** [comment]
Will follow-up support be provided?

**Comment by parisk** [comment]
There are no plans for this feature at the moment, but it could be materialized in the future, as there are valid use cases for it.

Right now we prefer to keep it simple, until we reach 1.0 within the next couple of months.

**Comment by tanyo520** [comment]
Thank you very much. I think this function is still necessary and I look forward to it.
