### ISSUE TITLE
After upgrading to 0.7 version, ceryx stop generating Let's Encrypt certificates

### ISSUE THREAD

**Issue by gurumark** [sourcelair/ceryx#79]
After upgrading to 0.7 version, all certificate generation started failing. After setting it to DEBUG true, I get the following in the ceryx log:
**************
2019/12/26 19:31:18 [error] 40#40: [lua] init_master.lua:67: generate_config(): auto-ssl: failed to create letsencrypt dir permissions: Executing command failed (exit code 1): chmod 777 /etc/resty-auto-ssl/letsencrypt 2>&1
Output: chmod: changing permissions of '/etc/resty-auto-ssl/letsencrypt': Operation not permitted
***************
Running the command manually in the directory did not help:
chmod -R 777 /etc/resty-auto-ssl/

The log still shows the same error and the routing to SSL requiring domains stopped as well.

Please advice.

Thanks in advance.

**Comment by parisk** [comment]
Thanks for reporting this @gurumark! We will investigate it and respond as soon as we confirm it or not.

**Comment by gurumark** [comment]
This issue has been fixed. It was not related to ceryx.
